### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by HimbeersaftLP** [BoxOfDevs/CommandShop#3]
### Todo until the plugin works:

- [x] Implement managing commands (add, remove etc.)
- [x] Add buying (the function itself)
- [x] Add buying with signs
- [x] Implement sign creation
- [x] Paying with EconomyAPI

### Todo until release:

- [x] Add buying with a command
- [x] Paying with items
- [x] Changeable messages __(Language file support will be added later on)__
- [x] Write a Wiki
- [x] Add command for adding commands to commands (<-- Such descriptive, much wow)
- [x] Sign buy confirmation with double-tap
- [x] Change sign's command when using _/cshop sign_ more than one time (easy)
- [x] Automatic sign deletion from config on break
- [x] A descriptive help command xD

### Todo until V2: 
- [ ] Automatic sign deletion from config when a sign breaks by breaking the attached block
- [ ] Add variables for args e.g. {arg1}, {arg2} and so on
- [ ] Support for different Economy plugins
- [ ] Execute as player with auto-perm management
- [ ] Multiple languages (selectable)

**Comment by NycuRO** [comment]
👍

**Comment by Thunder33345** [comment]
i highly recommend using a economy interface, so in the future it wouldnt be so hard to add more supports
and also what happen IF someone execute the command? 
- would they be blocked if they havent purchased it
- would they be needed buy it even if they have permission(of the command to be sold) to use it?
- would there be bypass permissions for admin?

i think the ability to execute commands after purchase would be neat or even a pay per use command

FYI there's a [Project Tab](https://github.com/BoxOfDevs/CommandShop/projects)

just my suggestions/opinions

**Comment by HimbeersaftLP** [comment]
> i highly recommend using a economy interface, so in the future it wouldnt be so hard to add more supports

I'll try, but for now, we'll just stick with EconomyAPI

> and also what happen IF someone execute the command?
would they be blocked if they havent purchased it
would they be needed buy it even if they have permission(of the command to be sold) to use it?
would there be bypass permissions for admin?

I thought it like this (for the one-time-executing one): You can choose between execute as player and from console. When you choose as player, you have to enter a permission which will then be given to the player, the command executed and then removed again when the player "buys" the command

> i think the ability to execute commands after purchase would be neat or even a pay per use command

I asked the requester about if the player buy it once or per execute: https://forums.pmmp.io/threads/command-shop.747/

**Comment by Ad5001** [comment]
I think it should be changable in the config.

**Comment by HimbeersaftLP** [comment]
I think it should be changeable per command

**Comment by HimbeersaftLP** [comment]
> i think the ability to execute commands after purchase would be neat or even a pay per use command

I just noticed that a feature like this would make no sense, since you could just set the command to `/setuperm {player} example.permission` then the player just has to pay for getting the perm and can then always execute the command

**Comment by HimbeersaftLP** [comment]
Just a few things missing O_O

**Comment by Thunder33345** [comment]
?

**Comment by HimbeersaftLP** [comment]
> Thunder33345 said:
> ?

Just a few things missing on the Todo list

**Comment by TheDragonRing** [comment]
"Add command for adding commands to commands":

What lol?

**Comment by Ad5001** [comment]
Functions implementation x)?

**Comment by TheDragonRing** [comment]
But we made functiond already.... No need to repeat it!!!!!!

**Comment by HimbeersaftLP** [comment]
No it supports executing multiple commands at once, but for now, it only works if you add more commands to the array manually, I need to make a command for that

**Comment by TheDragonRing** [comment]
I think I (partially) understand what you mean...

**Comment by HimbeersaftLP** [comment]
One (easy) more left and we can release 🥇

**Comment by TheRoyalBlock** [comment]
Nice!

**Comment by Ad5001** [comment]
Fixed everything ! You can release !

**Comment by HimbeersaftLP** [comment]
Thanks, I am stupid lol

**Comment by HimbeersaftLP** [comment]
I added some easy but necessary things to the ToDo list, so that our plugin gets more-likely approved

**Comment by Ultie0** [comment]
Sorry, I couldn't resist change the name of the label. 😛

**Comment by HimbeersaftLP** [comment]
xD

**Comment by Thunder33345** [comment]
i thought we own the command once we bought it and have unlimited uses

**Comment by HimbeersaftLP** [comment]
The whole point of the plugin is to allow modular shops for people who can't code plugins.

Example: Perm Shop, Shop for spezial Items, Pay for setting time to day....

**Comment by Thunder33345** [comment]
but set user permission isnt a good idea in some cases
what if you want to give player to tp to 0 80 0 while not giving them /tp?
what if you want to allow player buy /give {self} dirt 64 without giving them /give?

**Comment by HimbeersaftLP** [comment]
Hmmmm, okay, I'll take a look at it

**Comment by Thunder33345** [comment]
@HimbeersaftLP i think you can get away by making a custom command compactor/shortcut with permission
ex
/getdirt which will execute give dirt {player} 64
but they will need getdirt permission,
wait this sounds familiar, i guess you can put functions as a suggested enhancement

**Comment by HimbeersaftLP** [comment]
Yep, I think that really should be a nice feature in Functions, want to create a request issue there?

**Comment by Thunder33345** [comment]
@HimbeersaftLP wait which feature dosent exist in function?

**Comment by HimbeersaftLP** [comment]
I don't know, Functions is more confusing for me than C, HTML, php and JS together xD

**Comment by Ad5001** [comment]
LOL

**Comment by HimbeersaftLP** [comment]
@Ad5001 What? That's true xD

**Comment by Ultie0** [comment]
We need online Functions courses.

**Comment by HimbeersaftLP** [comment]
> We need online Functions courses.

Yep xD

**Comment by Ad5001** [comment]
Damned x)

**Comment by TheRoyalBlock** [comment]
@Ultie0 Lets put it into sites4code

**Comment by Thunder33345** [comment]
it's not very confusing at all

**Comment by LordJoshie** [comment]
See what I've used your plugin for ! 
This is amazing <3 Thank you guys <3<3<3<3


![image](https://cloud.githubusercontent.com/assets/17371144/23582302/8dd6bd22-00f5-11e7-8398-c97710ee304b.png)

**Comment by LordJoshie** [comment]
If I could add a suggestion, perhaps make it so it says "Are you sure you want to do this?" and then make so you have to tap again to confirm. 

that would be the coooooolessssssttttttt.

**Comment by HimbeersaftLP** [comment]
> See what I've used your plugin for !
> This is amazing <3 Thank you guys <3<3<3<3
>
> image

Awesome idea!

> If I could add a suggestion, perhaps make it so it says "Are you sure you want to do this?" and then make so you have to tap again to confirm.
>
> that would be the coooooolessssssttttttt.

Already on the ToDo list 😛

**Comment by LordJoshie** [comment]
@HimbeersaftLP  I love you <3 ;P  #NoHomo

**Comment by LordJoshie** [comment]
edit the to-do and remove the " Buy-Once-Use-Always-Command "  since you can set the command as 

setuperm {player} the.permission  

and then wallah... they can use it whenever they want. 

I've actually made use of the multiple ran commands and done

setuperm {player} a.perm.ission
as {player} the command
unsetuperm {player} a.perm.ission 

so they can only 1 time use it, but giving them the permission to do so for only that moment. 

did it this way, because I wasn't sure of a way to run the command as a player with op perms, as if it was Tap-To-Do how they have args like %pow (as console) %op (as player with op perms) or %p (the player) 

this is still my favorite plugin atm tho, since my server is mostly based on economy.

**Comment by HimbeersaftLP** [comment]
> edit the to-do and remove the " Buy-Once-Use-Always-Command " since you can set the command as

Okay

> did it this way, because I wasn't sure of a way to run the command as a player with op perms, as if it was Tap-To-Do how they have args like %pow (as console) %op (as player with op perms) or %p (the player)

Is on the ToDo list: "Execute as player with auto-perm management" :P

> this is still my favorite plugin atm tho, since my server is mostly based on economy.

Thanks <3 (#nohomo

btw, We are working on an "Ideas" section in the wiki, do you want to help us with that?

**Comment by LordJoshie** [comment]
I have so many ideas for plugins, or to improve existing ones.

Id love to!

**Comment by HimbeersaftLP** [comment]
> - [x] Add command for adding commands to commands (<-- Such descriptive, much wow)

Finally done, not tested yet thogh

**Comment by TheDragonRing** [comment]
Hey @LordJoshie, if you'd like to officially join as a beta-tester/helper apply at http://boxofdevs.com/apply.html

**Comment by Thunder33345** [comment]
i still doubt using permissions to allow commands as like my previous example

> but set user permission isnt a good idea in some cases
what if you want to give player to tp to 0 80 0 while not giving them /tp?
what if you want to allow player buy /give {self} dirt 64 without giving them /give?

**Comment by Ad5001** [comment]
@Thunder33345 Then you can use functions to use a custom command with the func permission.

**Comment by HimbeersaftLP** [comment]
> If I could add a suggestion, perhaps make it so it says "Are you sure you want to do this?" and then make so you have to tap again to confirm.
> 
> that would be the coooooolessssssttttttt.

Here we go:

> - [x] Sign buy confirmation with double-tap

Done that, and the command for adding commands to commands (xD) has been tested, too now

**Comment by HimbeersaftLP** [comment]
> - [x] Change sign's command when using /cshop sign more than one time (easy)

Done that

**Comment by TheRoyalBlock** [comment]
nice!

**Comment by HimbeersaftLP** [comment]
> Automatic sign deletion from config on break

Working  on that

also: WHO DELETED ALL THE COMMENTS?! 👎

**Comment by Vaults1** [comment]
*SHOCKING REACTION*

**Comment by Thunder33345** [comment]
for auto removing broken signs there should be an option for if someone want to have shop on a block

**Comment by HimbeersaftLP** [comment]
> for auto removing broken signs there should be an option for if someone want to have shop on a block

Wouldn't work cuz the plugin checks if it's a sign before executing the command, so it doesn't foreach through the whole sign config just when tapping a block, however we could add a setting wether or not to allow blocks too instead of only signs

**Comment by Thunder33345** [comment]
so that's a technically limit, i see...

**Comment by Vaults1** [comment]
> WHO DELETED ALL THE COMMENTS?! 👎

Probably HimbeerCloud™

**Comment by HimbeersaftLP** [comment]
> Probably HimbeerCloud™

No, RoyalCloud™:stuck_out_tongue:

**Comment by Vaults1** [comment]
MeowCloud™
UltiCloud™

**Comment by AvgZing** [comment]
Guess what! My dad's new work gave him 2 .net domains. He is using one, and he gave me the other! I set up https://royalclouds.net/

**Comment by AvgZing** [comment]
FYI the customer review on there are fake, all of the services are fake, but soon they will be real.

**Comment by HimbeersaftLP** [comment]
@LordJoshie and everyone else who cares: This plugin is finally completed a Poggit release will be submitted soon

**Comment by HimbeersaftLP** [comment]
@jerryzooyoyo Your plugin request has finally been finished lol

**Comment by AvgZing** [comment]
https://github.com/BoxOfDevs/CommandShop/projects/1
